"use client";

import { useState } from "react";
import { FileSpreadsheet, LoaderCircle, Upload, CheckCircle2, AlertCircle } from "lucide-react";

type Preview = { hypotheses: unknown[]; duplicates: unknown[]; issues: { sheetName: string; rowNumber: number; reason: string; title?: string }[]; skipped: number };
export default function ImportPage() {
  const [file, setFile] = useState<File>(); const [preview, setPreview] = useState<Preview>(); const [loading, setLoading] = useState(false); const [result, setResult] = useState<string>("");
  async function inspect() { if (!file) return; setLoading(true); setResult(""); const data = new FormData(); data.set("file", file); const response = await fetch("/api/import/preview", { method: "POST", body: data }); const body = await response.json(); setLoading(false); if (!response.ok) setResult(body.error); else setPreview(body); }
  async function commit() { if (!preview || !file) return; setLoading(true); const response = await fetch("/api/import/commit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, hypotheses: preview.hypotheses, issues: preview.issues }) }); const body = await response.json(); setLoading(false); setResult(response.ok ? `Импортировано: ${body.imported}` : body.error); }
  return <div className="mx-auto max-w-3xl space-y-6 px-4 py-6 lg:px-8"><div><p className="eyebrow">Разовый импорт</p><h1 className="mt-1 text-3xl font-bold">Перенесите данные из таблицы</h1><p className="mt-2 text-zinc-400">Поддерживаются .xlsx и CSV. Технические строки, `TBD`, скрытый ICE и ошибки формул не станут гипотезами.</p></div><section className="card"><label className="flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-white/15 bg-white/[0.025] px-6 py-10 text-center transition hover:border-[#d3f96a]/60"><FileSpreadsheet size={35} className="text-[#d3f96a]"/><strong className="mt-3">Выберите экспорт Google Sheets</strong><span className="mt-1 text-sm text-zinc-500">.xlsx или .csv, до 10 МБ</span><input type="file" accept=".xlsx,.csv" className="sr-only" onChange={(event) => { setFile(event.target.files?.[0]); setPreview(undefined); setResult(""); }}/></label>{file && <div className="mt-4 flex items-center justify-between rounded-lg bg-white/[0.04] p-3 text-sm"><span>{file.name}</span><button onClick={inspect} disabled={loading} className="inline-flex items-center gap-2 rounded-lg bg-[#d3f96a] px-3 py-2 font-bold text-[#151a0e] disabled:opacity-50">{loading && <LoaderCircle className="animate-spin" size={16}/>}Проверить</button></div>}{result && <p className="mt-3 text-sm font-medium text-[#d3f96a]">{result}</p>}</section>{preview && <section className="card"><div className="flex items-center gap-2"><CheckCircle2 className="text-[#d3f96a]"/><h2 className="text-xl font-bold">Предпросмотр импорта</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Новые гипотезы", preview.hypotheses.length], ["Дубликаты", preview.duplicates.length], ["Пропущено", preview.skipped], ["Требует разбора", preview.issues.length]].map(([label, value]) => <div className="rounded-lg border border-white/10 bg-white/[0.025] p-3" key={String(label)}><p className="text-2xl font-bold">{String(value)}</p><p className="text-xs text-zinc-500">{String(label)}</p></div>)}</div>{preview.issues.length > 0 && <div className="mt-5 rounded-lg border border-amber-300/20 bg-amber-300/10 p-4 text-sm text-amber-100"><div className="flex gap-2"><AlertCircle size={17}/><p><strong>Неоднозначности не угадываются.</strong> Они сохранятся в журнале импорта для разбора.</p></div><ul className="mt-3 list-disc pl-5">{preview.issues.slice(0, 5).map((issue) => <li key={`${issue.sheetName}-${issue.rowNumber}`}>{issue.sheetName}, строка {issue.rowNumber}: {issue.reason}</li>)}</ul></div>}<button onClick={commit} disabled={loading || !preview.hypotheses.length} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#d3f96a] px-4 py-3 font-bold text-[#151a0e] disabled:opacity-50"><Upload size={17}/>Подтвердить импорт</button></section>}</div>;
}
