import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleDotDashed, Clock3, ListPlus, Target } from "lucide-react";
import { StatusBadge } from "@/components/status";
import { getWorkspaceData } from "@/lib/workspace";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const data = await getWorkspaceData(); const hypotheses = data.hypotheses; const top = hypotheses.filter((item) => item.score !== null).slice(0, 5); const current = hypotheses.filter((item) => ["READY_FOR_PRIORITIZATION", "PRIORITIZED", "PLANNED", "IN_PROGRESS"].includes(item.status));
  const counts = { total: hypotheses.length, inProgress: hypotheses.filter((item) => item.status === "IN_PROGRESS").length, validated: hypotheses.filter((item) => item.status === "VALIDATED").length, unscored: hypotheses.filter((item) => item.score === null).length };
  return <div className="mx-auto max-w-7xl space-y-6 px-4 py-6 lg:px-8"><section className="grid gap-5 rounded-2xl border border-white/10 bg-[#161b23] p-6 lg:grid-cols-[1.35fr_.65fr]"><div><p className="eyebrow">Сегодня</p><h1 className="mt-2 max-w-xl text-3xl font-bold tracking-tight sm:text-4xl">Превратите следующую идею в понятный эксперимент</h1><p className="mt-4 max-w-xl text-zinc-400">Не заводите строки в Excel. Пройдите короткий сценарий: сформулируйте идею, выберите сигнал, оцените приоритет и поставьте дату результата.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/new" className="inline-flex items-center gap-2 rounded-lg bg-[#d3f96a] px-4 py-3 text-sm font-bold text-[#151a0e]"><ListPlus size={18}/>Создать гипотезу</Link><Link href="/hypotheses" className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-4 py-3 text-sm font-bold text-zinc-200 hover:bg-white/[0.06]">Открыть реестр<ArrowRight size={17}/></Link></div></div><div className="rounded-xl border border-white/10 bg-[#0d1015] p-5"><p className="text-xs font-bold uppercase tracking-wider text-zinc-500">Следующее действие</p>{current[0] ? <><p className="mt-3 text-lg font-bold">{current[0].title}</p><p className="mt-2 text-sm text-zinc-400">{current[0].score === null ? "Нужно оценить по RICE" : `RICE ${current[0].score} · ${current[0].funnelStage?.name ?? "этап не задан"}`}</p><Link href={`/hypotheses/${current[0].id}`} className="mt-5 inline-flex text-sm font-bold text-[#d3f96a]">Открыть карточку →</Link></> : <><p className="mt-3 text-lg font-bold">Начните с одной идеи</p><p className="mt-2 text-sm text-zinc-400">Мастер доведёт её до плана проверки.</p></>}</div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["В реестре", counts.total, Target], ["В работе", counts.inProgress, Clock3], ["Проверено", counts.validated, CheckCircle2], ["Ждут оценки", counts.unscored, CircleDotDashed]].map(([label, value, Icon]) => { const Component = Icon as typeof Target; return <Link href="/hypotheses" className="card group p-4 hover:border-white/25" key={String(label)}><Component className="text-[#d3f96a]" size={18}/><p className="mt-6 text-3xl font-bold">{String(value)}</p><p className="mt-1 text-sm text-zinc-500 group-hover:text-zinc-300">{String(label)}</p></Link>; })}</section>
  <section className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="card"><div className="flex items-center justify-between"><div><p className="eyebrow">Приоритет</p><h2 className="mt-1 text-xl font-bold">Что делать следующим</h2></div><Link href="/hypotheses" className="text-sm font-bold text-[#d3f96a]">Весь реестр →</Link></div><div className="mt-5 space-y-2">{top.length ? top.map((item, index) => <Link href={`/hypotheses/${item.id}`} className="flex items-center gap-3 rounded-lg p-3 transition hover:bg-white/[0.055]" key={item.id}><span className="grid h-7 w-7 place-items-center rounded-md bg-white/[0.07] text-sm font-bold text-[#d3f96a]">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{item.title}</p><p className="mt-0.5 text-xs text-zinc-500">{item.funnelStage?.name ?? "Без этапа"}</p></div><span className="font-mono font-bold text-[#d3f96a]">{item.score}</span><StatusBadge status={item.status}/></Link>) : <p className="py-10 text-center text-zinc-500">У оценки появится смысл, когда в реестре будет первая гипотеза.</p>}</div></div><div className="card"><p className="eyebrow">Цель</p><h2 className="mt-2 text-xl font-bold">{data.objectives[0]?.title ?? "Цель не задана"}</h2><p className="mt-4 text-sm text-zinc-500">{data.objectives[0]?.metric}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full w-1/4 rounded-full bg-[#d3f96a]"/></div><p className="mt-3 text-sm text-zinc-400">{data.objectives[0]?.currentValue?.toLocaleString("ru-RU")} <span className="mx-1 text-zinc-600">→</span> {data.objectives[0]?.targetValue?.toLocaleString("ru-RU")}</p></div></section>
  <section className="card"><div className="flex items-center justify-between"><div><p className="eyebrow">Покрытие воронки</p><h2 className="mt-1 text-xl font-bold">Где уже есть эксперименты</h2></div><Link href="/new" className="text-sm font-bold text-[#d3f96a]">Добавить в этап →</Link></div><div className="mt-5 grid gap-3 md:grid-cols-4">{data.stages.map((stage) => { const amount = hypotheses.filter((item) => item.funnelStageId === stage.id).length; return <div key={stage.id} className="rounded-lg border border-white/10 bg-white/[0.025] p-4"><p className="text-2xl font-bold">{amount}</p><p className="mt-2 text-sm text-zinc-400">{stage.name}</p></div>; })}</div></section></div>;
}
