"use client";

import Link from "next/link";
import { useState } from "react";
import { Download, Search } from "lucide-react";
import { StatusBadge } from "@/components/status";
import type { Status } from "@/lib/hypotheses";

type Item = { id: string; title: string; hypothesis: string | null; score: number | null; status: Status; dueDate: string | null; objective: { title: string } | null; funnelStage: { name: string } | null };
export function HypothesisRegistry({ items }: { items: Item[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL");
  const visible = items.filter((item) => (status === "ALL" || item.status === status) && `${item.title} ${item.hypothesis ?? ""} ${item.funnelStage?.name ?? ""}`.toLocaleLowerCase("ru").includes(query.toLocaleLowerCase("ru")));
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Реестр</p><h1 className="mt-1 text-3xl font-bold">Все гипотезы</h1><p className="mt-2 text-zinc-400">Здесь принимают решение: что оценить, запланировать и проверить.</p></div><a href="/api/hypotheses/export" className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-sm font-bold hover:bg-white/[0.06]"><Download size={16}/>Экспорт CSV</a></div><div className="card grid gap-3 p-3 sm:grid-cols-[1fr_220px]"><label className="relative"><Search size={17} className="absolute left-3 top-3.5 text-zinc-500"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-lg py-3 pl-10 pr-4 outline-none ring-[#d3f96a]/30 focus:ring-2" placeholder="Поиск по идеям, гипотезам и этапам"/></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg px-3 py-3 outline-none"><option value="ALL">Все статусы</option><option value="IDEA">Идеи</option><option value="READY_FOR_PRIORITIZATION">К оценке</option><option value="PRIORITIZED">Приоритизированы</option><option value="PLANNED">Запланированы</option><option value="IN_PROGRESS">В работе</option><option value="VALIDATED">Проверены</option></select></div><p className="text-sm text-zinc-500">Найдено: {visible.length} из {items.length}</p><div className="overflow-hidden rounded-xl border border-white/10 bg-[#161b23]"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[0.03] text-xs uppercase tracking-wide text-zinc-500"><tr><th className="p-4">Идея</th><th className="p-4">Контекст</th><th className="p-4">RICE</th><th className="p-4">Статус</th><th className="p-4">Срок</th></tr></thead><tbody className="divide-y divide-white/10">{visible.map((item) => <tr key={item.id} className="transition hover:bg-white/[0.035]"><td className="max-w-md p-4"><Link href={`/hypotheses/${item.id}`} className="font-semibold hover:text-[#d3f96a]">{item.title}</Link><p className="mt-1 truncate text-xs text-zinc-500">{item.hypothesis || "Нужно описать гипотезу"}</p></td><td className="p-4 text-zinc-400"><p>{item.objective?.title ?? "Без цели"}</p><p className="mt-1 text-xs text-zinc-500">{item.funnelStage?.name ?? "Этап не задан"}</p></td><td className="p-4"><span className="font-mono font-bold text-[#d3f96a]">{item.score ?? "—"}</span></td><td className="p-4"><StatusBadge status={item.status}/></td><td className="p-4 text-zinc-400">{item.dueDate ? new Date(item.dueDate).toLocaleDateString("ru-RU") : "—"}</td></tr>)}{visible.length === 0 && <tr><td colSpan={5} className="p-12 text-center text-zinc-500">Ничего не найдено. Измените поиск или создайте новую гипотезу.</td></tr>}</tbody></table></div></div></div>;
}
